### ISSUE TITLE
rhythmbox name is copyrighted

### ISSUE THREAD

**Issue by fossfreedom** [irmen/synthesizer#1]
Hi,

  just a quick one - your project is the same name as the Gnome based project - https://github.com/GNOME/rhythmbox

  As far as I know "rhythmbox" is copyrighted by GNOME.

suggest another name for your project might prevent confusion etc.

thanks.

**Comment by irmen** [comment]
I doubt that my tiny python script that in no way is a multimedia player or library manager, will confuse anybody, but  I'll add a ref to the readme.

**Comment by irmen** [comment]
Because this is now doing more than just mixing rhythm tracks I've renamed it to 'synthesizer' alltogether

**Comment by fossfreedom** [comment]
good name! :+1:
