### ISSUE TITLE
make python cffi miniaudio interface a separate project

### ISSUE THREAD

**Issue by faroit** [irmen/synthesizer#10]
I just found this project and it looks pretty great to me. 
The python community is still looking for a fast interface to audio decoding lib which is easy to install (libsndfile) but also supports codecs such as mp3 (sox, ffmpeg). There is not yet a solution to have both.

the python cffi interface for miniaudio looks great. Have you considered making this a separate project and maybe package the lib on conda or as a pip wheel so that it works out-of-the-box on multiple platforms?

Btw, I am the maintainer of the https://github.com/faroit/awesome-python-scientific-audio and I would love to add your projects there. Are they ready for prime time?

**Comment by irmen** [comment]
Hi thanks for your interest in the project!
While sharing the git repo with my synthesizer code, miniaudio is packaged on its own already: https://pypi.org/project/miniaudio/  

I'm fairly happy with the state of the code as it is now, and it should be usable in prime time (if not I consider it a bug). However some important features are still lacking as noted on the readme. I'm not too sure about the sound recording aspect, but I do want to expose the audio format conversion functions in an update soon

I created a binary wheel for what I think should be the most common windows target (py37 64 bit) I'm not really able to create more myself. Not explored the conda route for this package yet.  I guess if we take this forward, the miniaudio bindings should really get their own git repo

**Comment by faroit** [comment]
Great, I will give it a try soon and see how for I get with conda packaging.

**Comment by irmen** [comment]
@faroit the project is now in its own git repo as well https://github.com/irmen/pyminiaudio    by all means, add the project to your list! :smile:

**Comment by faroit** [comment]
That's great. I will give it a try this weekend and will check if I can add it to my list and the benchmarks
