### ISSUE TITLE
capture support for miniaudio

### ISSUE THREAD

**Issue by cameronmaske** [irmen/synthesizer#11]
Hi @irmen 

First off, thanks for your effort on this whole codebase. 

I noticed under your `pyminiaudio/README.md` your TODOs mention that the `the recording capabilities of miniaudio aren't exposed yet`. If you are open too contributions, I would love to do work towards this and implement basic capture functionality. 

If you have any guidance, thoughts, or advice, I would love to hear it. 

So far, I've taken a [very simple go at it](https://github.com/irmen/synthesizer/compare/master...cameronmaske:capture?expand=1). 

~~I'm a newbie when it comes to `C` (I haven't used `cffi` before) so any advice on how to cast the [`pInput`](https://github.com/irmen/synthesizer/blob/master/pyminiaudio/miniaudio.py#L811) to some sort of [`bytes`](https://github.com/irmen/synthesizer/compare/master...cameronmaske:capture?expand=1#diff-c0d62f91cb259e32276db2fd8fec2d71R12) (I'm ultimately trying to get into `numpy.array`) would be appreciated.~~ [This approach seems to work](https://github.com/irmen/synthesizer/compare/irmen:b0a6676...cameronmaske:1d887b7#diff-d46ed69bc93dc3f8f6c0127a8a2e583eR875)

**Comment by irmen** [comment]
Thanks for the message. Contributions are very much welcome!  I'll have a look soon (and update here afterwards)

**Comment by irmen** [comment]
You'll have to rebase this I think. Feel free to put it into a Pullrequest as well.

I don't want to introduce a hard numpy dependency in this library.
Maybe an optional one.  See _bytes_from_generator_samples()

**Comment by irmen** [comment]
Thanks for the PR
(Once it's merged I'm strongly considering splitting off pyminiaudio into its own separate github repo)

**Comment by irmen** [comment]
Unfortunately my microphone is not working properly atm but I managed to record a sound clip of a youtube video playing, using the modified capture.py demo script.  And the duplex script created a huge echo chamber :)

Right. I will now split this into its own repository and create a new release

**Comment by irmen** [comment]
@cameronmaske pyminiaudio has now been moved to https://github.com/irmen/pyminiaudio
