### ISSUE TITLE
Readme: how to run instrctions

### ISSUE THREAD

**Issue by jaywalkerpaz** [irmen/synthesizer#15]
hello and thanks, how can this synth be compiled and run?

**Comment by irmen** [comment]
Hi!  I am afraid it's not entirely clear to me what you are asking.
In the examples directory there are various example programs that you may study to see how you could use the library. The synthesizer (the keyboard GUI) is also in there.
Other than that, you'll have to read the source and code comments in the library I'm afraid - I haven't written any documentation beside that.

**Comment by jaywalkerpaz** [comment]
Thank you for your quick reply! I saw the screenshot of synthplayer.synth
and want to give it a go, see how sounds respond, and see if I can tweak
the code. To run, do I just go to the synthplayer dir and ./synth.py? That
doesn't seem to work for me. Im on a mac, not sure if that's a limitation?
Thanks!

**Comment by irmen** [comment]
"synthplayer" is a _library_, not a stand alone application. You'll have to install it in your python environment, and then program your own application to use it. That's why I pointed you at the set of examples that you can study.

It should work just fine on Mac.

**Comment by jaywalkerpaz** [comment]
Thank you I gathered that as much from your first message which was useful
to know. I guess I misunderstood it being a library vs a working tool! And
I'm thankful that you made this library.

In that case, you may consider a working example to get people up and
running? I'm not trying to be lazy about this but as I'm learning python,
it would be nice to see it all in action, and then be like, oh yeah, here
are some more amazing tools now that you have a basic one built! I'll still
try getting things going with this and see what I can pull together..

**Comment by irmen** [comment]
As I said the examples directory already contains a few working example applications. The keyboard GUI synthesizer being one of them. There is also a streaming internet radio application. I really don’t get what you are suggesting to do? What do you think is lacking?

**Comment by jaywalkerpaz** [comment]
Ohh gotcha, I'm sorry for the confusion. I figured out I needed to install
matplotlib and miniaudio. Then I went to the main dir and did: python
/examples/keyboard_gui.py (before I was cd'ing into the examples folder and
running it from there. So finally got it to work! Thank you and apologies
for being a newb and not really figuring out how to get things going. Very
nice project, very complete, awesome features.

**Comment by irmen** [comment]
I kinda assume people trying / using this project are fairly familiar with Python and how to install packages.

matplotlib and miniaudio and several others, are listed in the requirements.txt dependency file. But yeah perhaps I can mention that more.

You can run the examples just fine from their own directory, if you properly installed the synthplayer library first (python setup.py install / pip install -e . / pip install synthplayer    pick your poison)  

That said, glad you got things to work and that you like my library. I appreciate the feedback.
