### ISSUE TITLE
JACK CV?

### ISSUE THREAD

**Issue by mxmilkiib** [irmen/synthesizer#16]
Would you consider support for JACK backend [CV ports](https://linuxmusicians.com/viewtopic.php?f=1&t=20701)? It's port property metadata that marks a JACK client port for a real-time control float signal, i.e., it's then expected its output can act like a sometimes "DC" modular hardware synth CV signal. Here's an [example project](https://github.com/mxmilkiib/carla-lv2-jack-nsm).

**Comment by irmen** [comment]
It will have to be done via one of the existing backends.

the miniaudio backend supports Jack.   Maybe you can try that out?     It could be that you have to tell miniaudio somewhere that it has to use Jack - if there are other audio libraries on the system that it  prefers such as pulse

**Comment by mxmilkiib** [comment]
Good point. I have [asked](https://github.com/mackron/miniaudio/issues/268) upstream.

**Comment by irmen** [comment]
oh- I know too little about this stuff to know if JACK that you mention is any different from the jack system that miniaudio already supports. Their author will probably give the solution!

**Comment by mxmilkiib** [comment]
Yes, the same [JACK](https://github.com/jackaudio/jackaudio.github.com/wiki) :)

**Comment by irmen** [comment]
well aren't you set then?   Make sure you make miniaudio to select its Jack backend.   Support is already there.  (although untested)

**Comment by mxmilkiib** [comment]
There are different levels of support for JACK that an app (or library) can have. Client metadata is one of the things that isn't necessary but provides port names. CV support would go a bit further though because a specific property in itself, and it's not just for a standard audio style signal.

**Comment by irmen** [comment]
i glanced at the cv ports page but this is all WAY over my head. If the author of miniaudio itself adds this to the library I will still need a lot of help (I think??? based on the complexity of that page about Cv ports) to expose this via pyminiaudio first and then this synthesizer library.... beginning with the purpose of it all and how it could be accessible from python

**Comment by irmen** [comment]
As I'm not going to pursue this myself in pyminiaudio, I'm closing this topic for the time being.
