### ISSUE TITLE
add a VolumeFilter to a StreamingSample

### ISSUE THREAD

**Issue by cyberic99** [irmen/synthesizer#17]
Hi,
First, thank you for this project !
It lacks a bit of documentation, but following the code and the examples is easy enough because the code is very well written.

I'd like to play and mix to samples.
I'd like to control their volume externally (independently), and the playback volume will change during the playback.

But it doesn't seem possible to use ``add_filter()`` on a ``StreamingSample``, am I right?

Is there a way to use regular ``Samples`` and alter their volume while they are playing?

Thank you

**Comment by irmen** [comment]
Yeah this is not provided at this time for Samples, just for the output stream as a whole (using add_filter)

So may I suggest you have a look at subclassing the Sample class yourself and implementing some sort of volume controlled variant to it? You should look at the chunked_frame_data method.  There are 2 examples that perhaps could get you started: StreamingSample and StreamingOscSample

**Comment by cyberic99** [comment]
I have subclassed Sample, I can manipulate the audio data in the callback.

Thank you and thank you for ``synthesizer`` !

**Comment by irmen** [comment]
@cyberic99 yay! I am glad you got it sorted.
Would you perhaps like to share your work as a pull-request ? Or is it too special for your own use case?

**Comment by cyberic99** [comment]
I think it is not generic enough to require a pull request.
But it could be useful to add an example
I'll do some cleanup then I'll provide an example

**Comment by cyberic99** [comment]
Here is my short example:

It is kind of ugly, and I shamelessly copied ``chunked_frame_data()``, but maybe it can be used as a starting pojnt for dynamic sample alteration.
The volume of the sample will change from 1 to 0 and back to 1 every second:
```python
#!/usr/bin/env python3

import audioop
import time
import wave
from synthplayer.playback import Output
from synthplayer.soundapi import best_api, available_mix_play_apis
from synthplayer.streaming import StreamingSample

print("synthplayer available APIs:", available_mix_play_apis)
from synthplayer.soundapi import MiniaudioMixed as sapi

class DynamicSample(StreamingSample):
    from typing import Optional, Union, Callable, BinaryIO, Generator, List
    """
    A sound Sample that does NOT load the full source file/stream into memory,
    but loads and produces chunks of it as they are needed.
    Can be used for the realtime mixing output mode to allow
    on demand decoding and streaming of large sound files.
    """
    def __init__(self, wave_file: Optional[Union[str, BinaryIO]] = None, name: str = "", volume: float = 1.0) -> None:
        super().__init__(wave_file, name)
        self.volume = volume

    def chunked_frame_data(self, chunksize: int, repeat: bool = False, stopcondition: Callable[[], bool] = lambda: False) -> Generator[memoryview, None, None]:
        silence = b"\0" * chunksize
        while True:
            audiodata = self.wave_stream.readframes(chunksize // self.samplewidth // self.nchannels)
            if not audiodata:
                if repeat:
                    self.wave_stream.rewind()
                else:
                    break   # non-repeating source stream exhausted
            if len(audiodata) < chunksize:
                audiodata += silence[len(audiodata):]
            # !! change volume dynamically !!
            audiodata = audioop.mul(audiodata, self.samplewidth, self.volume)
            yield memoryview(audiodata)

filename = "/tmp/song.wav"

out = Output()
out.audio_api = sapi(out.samplerate, out.samplewidth, out.nchannels, out.frames_per_chunk)
# the sample rate must match the rate of 'out'
print("out:", out)
print("out audio_api:", out.audio_api)
print(f"synthplayer out: {out}. Frames per chunk: {out.frames_per_chunk}")

vol = 1.0
smp = DynamicSample(filename, "sample", 1.0)

out.play_sample(smp)
for i in range(0, 50):
    if i % 2 == 0:
        vol = 1.0
    else:
        vol = 0.0
    smp.volume = vol
    print(f"time={i} vol={vol}")
    time.sleep(1)
```

**Comment by irmen** [comment]
I've added an example based on your code 7163f5e6dc0d404a69e6808641e7296bc23413d0

This is enough to resolve your initial question I think? Closing the issue now.

**Comment by cyberic99** [comment]
> This is enough to resolve your initial question I think? Closing the issue now.

Yes it is. Thank you very much and thank you for this project
