### ISSUE TITLE
Mixing two sine sounds like saw?

### ISSUE THREAD

**Issue by pltrdy** [irmen/synthesizer#18]
Hi,

I lack sound design theory / signal theory so this might sound dumb.

In an attempt to create chords I am mixing different frequencies of sine waves.
However, the result sounds more like a sawtooth wave.
Is that possible to mix sines and get a sine-sounding chord ?

Code example:
```python
from synthplayer.synth import WaveSynth
from synthplayer.playback import Output

synth_player = WaveSynth()


def sine(*args, **kwargs):
    return synth_player.sine(*args, **kwargs)


def get_sample():
    sine1 = sine(440, 2)
    sine2 = sine(220, 1)
    sine1.mix(sine2)
    return sine1


with Output(nchannels=1, mixing="sequential", queue_size=2) as out:
    out.play_sample(get_sample())
    out.wait_all_played()

```

**Comment by irmen** [comment]
I lack the same background btw!!

Mixing waveforms can yield very unexpected results.

If you're after a "well sounding" waveform where several sine waves have been mixed together, you're probably looking for "harmonics".  See WaveSynth.harmonics() that mixes sine waves into a harmonic waveform:

https://github.com/irmen/synthesizer/blob/7163f5e6dc0d404a69e6808641e7296bc23413d0/synthplayer/synth.py#L237

example code: https://github.com/irmen/synthesizer/blob/master/examples/synth_demo.py#L469



For CHORDS,
as far as I know, only specific combinations of frequencies result in a nice "chord" waveform.
Here are some examples: https://en.wikipedia.org/wiki/Major_seventh_chord

The major 7th chords are implemented in the wavesynth
Here is some example code that plays chords:
https://github.com/irmen/synthesizer/blob/7163f5e6dc0d404a69e6808641e7296bc23413d0/examples/synth_demo.py#L487

**Comment by irmen** [comment]
By the way,
the wavesynth indeed has several methods to generate square / triangle / sawtooth waveforms using mixing of sine wave harmonics.

For instance:  https://github.com/irmen/synthesizer/blob/7163f5e6dc0d404a69e6808641e7296bc23413d0/synthplayer/synth.py#L205

Here's  a simple overview of the harmonics involved in constructing some of those waveforms
![image](https://user-images.githubusercontent.com/1771820/132107344-111bf7a8-1856-4366-b532-b3b4cc5f47c8.png)

google "sawtooth harmonics" for a lot more info

**Comment by irmen** [comment]
Closing this issue for now. Feel free to re-open if you have new problems.

**Comment by pltrdy** [comment]
Thanks for the clarifications!
