### ISSUE TITLE
Misuse of sounddevice.stop()

### ISSUE THREAD

**Issue by mgeier** [irmen/synthesizer#3]
First of all, nice project!

I had a quick look at the code, and I saw that you are using `sounddevice.stop()` a few times.

However, that doesn't do anything unless you were using `sounddevice.play()`, `sounddevice.rec()` or `sounddevice.playrec()` before.

I guess it doesn't hurt, but you probably expect it to do something that it doesn't?

**Comment by irmen** [comment]
Hmm, I assumed it doesn't hurt to call stop() even when nothing was playing?
I call it to make sure that if there is a sound playing, it will stop (f.ex. when closing the audio api).

**Comment by mgeier** [comment]
It probably doesn't hurt, but it might be misleading.

Calling `stop()` doesn't stop all sound, it only stops the current invocation of `play()`/`rec()`/`playrec()` (none of which you are actually using).

**Comment by irmen** [comment]
Oh okay!  Well then I guess the call to stop() is redundant, or is there something else I should do before tearing down the sound device?

**Comment by mgeier** [comment]
It's not even redundant in your case, its just superfluous.

> is there something else I should do before tearing down the sound device?

Theoretically, calling `close()` on the stream should be enough, but we had cases with older Portaudio versions where `stop()` (on the stream, I'm not talking about `sounddevice.stop()`) was necessary before that, see https://github.com/spatialaudio/python-sounddevice/issues/87.

If it makes sense in your code, you could also try to use the stream as a context manager.

But even if you forget to close a stream it's not really a problem; when the Python interpreter shuts down, the PortAudio library is automatically terminated correctly.

**Comment by irmen** [comment]
I've overhauled the code and in the process these calls to sounddevice.stop() have been removed as well.
